run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - gci
    - gofmt

linters-settings:
    gci:
      sections:
        - standard
        - default
        - prefix(generate_cart)
      custom-order: true